apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: fastapi-image-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd/git-creds"
    gitConfig:
      repository: "https://github.com/jdht1992/fastapi-argocd.git"   # ← matches Application
      branch: main
  applicationRefs:
    - namePattern: "gitops-argocd-test"
      images:
        - alias: "fastapi"
          imageName: "docker.io/jdhet/fastapi-argo"
          commonUpdateSettings:
            updateStrategy: digest
            allowTags: "latest"