apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-argo-deployment
  namespace: argocd-demo-ns
  labels:
    app: fastapi-test-argo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-test-argo
  template:
    metadata:
      labels:
        app: fastapi-test-argo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: fastapi-container
        image: docker.io/jdhet/fastapi-argo:latest
        ports:
        - containerPort: 80
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "500m", memory: "512Mi" }

