# Kubernetes-manifest/fastapi/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: docker.io/jdht1992/fastapi-argo
    newTag: latest    # Image Updater overrides this with sha256
