apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fastapi-deployment.yaml    # ← match actual filenames
  - fastapi-service.yaml
images:
  - name: docker.io/jdht1992/fastapi-argo
    newTag: latest
